version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: